/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipodecarnetdigital.view;

import ec.edu.espe.datamanager.controller.Persistance;
import ec.edu.espe.datamanager.utils.MongoDBManager;
import ec.edu.espe.datamanager.utils.NSQLDBManager;
import javax.swing.JOptionPane;
import prototipodecarnetdigital.controller.TablasController;

/**
 *
 * @author BryanPC
 */
public class FrmActualizar extends javax.swing.JFrame {

    NSQLDBManager mongo;
    Persistance cloud;

    /**
     * Creates new form FrmActualizar
     */
    public FrmActualizar() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtOldName.setEnabled(false);
        txtOldID.setEnabled(false);
        txtOldCorreo.setEnabled(false);
        txtOldCarrera.setEnabled(false);
        txtOldDirección.setEnabled(false);
        txtOldEdad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtOldID = new javax.swing.JTextField();
        txtOldCarrera = new javax.swing.JTextField();
        txtOldCorreo = new javax.swing.JTextField();
        txtNewCorreo = new javax.swing.JTextField();
        txtOldDirección = new javax.swing.JTextField();
        txtNewDireccion = new javax.swing.JTextField();
        txtOldEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEdadActualizar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        cmbCarrera = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel1.setText("ACTUALIZAR DATOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Nuevo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        txtOldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtOldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Anterior");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        txtNewName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewNameKeyTyped(evt);
            }
        });
        jPanel1.add(txtNewName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 230, -1));
        jPanel1.add(txtOldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 230, -1));
        jPanel1.add(txtOldCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 230, -1));
        jPanel1.add(txtOldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 230, -1));
        jPanel1.add(txtNewCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 230, -1));
        jPanel1.add(txtOldDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 230, -1));
        jPanel1.add(txtNewDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 230, -1));
        jPanel1.add(txtOldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 50, -1));

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombres", "ID", "Correo", "Carrera", "Dirección", "Edad"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 810, 160));

        btnShow.setText("Mostrar");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 76, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel9.setText("Edad:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 30, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel8.setText("Dirección:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel6.setText("Carrera:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel7.setText("Correo Institucional:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel5.setText("ID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel2.setText("Nombres y Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btnEdadActualizar.setText("Actualizar");
        btnEdadActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdadActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdadActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoActualizarDatos.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        spnEdad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnEdadKeyTyped(evt);
            }
        });
        jPanel1.add(spnEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologías de la Información", "Software" }));
        jPanel1.add(cmbCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 230, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizarDatos11.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldNameActionPerformed

    }//GEN-LAST:event_txtOldNameActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        TablasController studentC = new TablasController();
        tblStudent.setModel(studentC.tableStudent());
        MongoDBManager.getMongoC().close();
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmMenuPrincipal menu = new FrmMenuPrincipal();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEdadActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdadActualizarActionPerformed
        TablasController studentC = new TablasController();
        mongo = new MongoDBManager();
        cloud = new MongoDBManager();
        mongo.openConection("Name");
        String carrera = cmbCarrera.getSelectedItem().toString();
        String edad = spnEdad.getValue().toString();

        int n = JOptionPane.showConfirmDialog(null, "Seguro que desea actualizar estos datos?", "Actualizar", JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION) {

            cloud.update("Name", txtOldName.getText(), txtNewName.getText());     
            cloud.update("ID", txtOldID.getText(), txtOldID.getText());
            cloud.update("Correo", txtOldCorreo.getText(), txtNewCorreo.getText());
            cloud.update("Career", txtOldCarrera.getText(), carrera);
            cloud.update("Address", txtOldDirección.getText(), txtNewDireccion.getText());
            String old = txtOldEdad.getText();
            cloud.update("Age", old, edad);
            tblStudent.setModel(studentC.tableStudent());
            JOptionPane.showMessageDialog(null, "Datos Actualizados.");
            MongoDBManager.getMongoC().close();

        } else if (n == JOptionPane.NO_OPTION) {
            
            JOptionPane.showMessageDialog(null, "Datos No Actualizados.");

        }


    }//GEN-LAST:event_btnEdadActualizarActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        int seleccionar = tblStudent.rowAtPoint(evt.getPoint());
        txtOldName.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 0)));
        txtNewName.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 0)));
        txtOldID.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 1)));
        txtOldCorreo.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 2)));
        txtNewCorreo.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 2)));
        txtOldCarrera.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 3)));
        cmbCarrera.setToolTipText(String.valueOf(tblStudent.getValueAt(seleccionar, 3)));
        txtOldDirección.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 4)));
        txtNewDireccion.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 4)));
        txtOldEdad.setText(String.valueOf(tblStudent.getValueAt(seleccionar, 5)));
        spnEdad.setToolTipText(String.valueOf(tblStudent.getValueAt(seleccionar, 5)));
    }//GEN-LAST:event_tblStudentMouseClicked

    private void txtNewNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewNameKeyTyped
        char validate = evt.getKeyChar();

        if (Character.isDigit(validate)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar letras.");
        }
    }//GEN-LAST:event_txtNewNameKeyTyped

    private void spnEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnEdadKeyTyped
        if (spnEdad.getValue().toString().length() <= 0) {
            JOptionPane.showMessageDialog(null, "No se admiten numeros negativos.");
            evt.consume();
        }
    }//GEN-LAST:event_spnEdadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdadActualizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtNewCorreo;
    private javax.swing.JTextField txtNewDireccion;
    private javax.swing.JTextField txtNewName;
    private javax.swing.JTextField txtOldCarrera;
    private javax.swing.JTextField txtOldCorreo;
    private javax.swing.JTextField txtOldDirección;
    private javax.swing.JTextField txtOldEdad;
    private javax.swing.JTextField txtOldID;
    private javax.swing.JTextField txtOldName;
    // End of variables declaration//GEN-END:variables
}
